// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Button implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject buttonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Button";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		Selected("Selected"),
		KeyString("KeyString"),
		KeyInt("KeyInt"),
		Button_Root("MyFirstModule.Button_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Button(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Button(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject buttonMendixObject)
	{
		if (buttonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, buttonMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.buttonMendixObject = buttonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Button initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Button(context, mendixObject);
	}

	public static myfirstmodule.proxies.Button load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Button.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Button> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Button.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Selected
	 */
	public final java.lang.Boolean getSelected()
	{
		return getSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of Selected
	 */
	public final java.lang.Boolean getSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Selected.toString());
	}

	/**
	 * Set value of Selected
	 * @param selected
	 */
	public final void setSelected(java.lang.Boolean selected)
	{
		setSelected(getContext(), selected);
	}

	/**
	 * Set value of Selected
	 * @param context
	 * @param selected
	 */
	public final void setSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selected)
	{
		getMendixObject().setValue(context, MemberNames.Selected.toString(), selected);
	}

	/**
	 * @return value of KeyString
	 */
	public final java.lang.String getKeyString()
	{
		return getKeyString(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyString
	 */
	public final java.lang.String getKeyString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KeyString.toString());
	}

	/**
	 * Set value of KeyString
	 * @param keystring
	 */
	public final void setKeyString(java.lang.String keystring)
	{
		setKeyString(getContext(), keystring);
	}

	/**
	 * Set value of KeyString
	 * @param context
	 * @param keystring
	 */
	public final void setKeyString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keystring)
	{
		getMendixObject().setValue(context, MemberNames.KeyString.toString(), keystring);
	}

	/**
	 * @return value of KeyInt
	 */
	public final java.lang.Integer getKeyInt()
	{
		return getKeyInt(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyInt
	 */
	public final java.lang.Integer getKeyInt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.KeyInt.toString());
	}

	/**
	 * Set value of KeyInt
	 * @param keyint
	 */
	public final void setKeyInt(java.lang.Integer keyint)
	{
		setKeyInt(getContext(), keyint);
	}

	/**
	 * Set value of KeyInt
	 * @param context
	 * @param keyint
	 */
	public final void setKeyInt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer keyint)
	{
		getMendixObject().setValue(context, MemberNames.KeyInt.toString(), keyint);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Button_Root
	 */
	public final myfirstmodule.proxies.Root getButton_Root() throws com.mendix.core.CoreException
	{
		return getButton_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Button_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Root getButton_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Button_Root.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Button_Root
	 * @param button_root
	 */
	public final void setButton_Root(myfirstmodule.proxies.Root button_root)
	{
		setButton_Root(getContext(), button_root);
	}

	/**
	 * Set value of Button_Root
	 * @param context
	 * @param button_root
	 */
	public final void setButton_Root(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Root button_root)
	{
		if (button_root == null) {
			getMendixObject().setValue(context, MemberNames.Button_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Button_Root.toString(), button_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return buttonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Button that = (myfirstmodule.proxies.Button) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
