// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Button_Click_KeyIntBuilder(
		myfirstmodule.proxies.Root _root
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Button_Click_KeyInt");
		builder = builder.withParam("Root", _root);
		return builder;
	}

	public static void aCT_Button_Click_KeyInt(
		IContext context,
		myfirstmodule.proxies.Root _root
	)
	{
		aCT_Button_Click_KeyIntBuilder(
				_root
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Button_Click_KeyStringBuilder(
		myfirstmodule.proxies.Root _root
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Button_Click_KeyString");
		builder = builder.withParam("Root", _root);
		return builder;
	}

	public static void aCT_Button_Click_KeyString(
		IContext context,
		myfirstmodule.proxies.Root _root
	)
	{
		aCT_Button_Click_KeyStringBuilder(
				_root
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Button_SaveBuilder(
		myfirstmodule.proxies.Button _button
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Button_Save");
		builder = builder.withParam("Button", _button);
		return builder;
	}

	public static void aCT_Button_Save(
		IContext context,
		myfirstmodule.proxies.Button _button
	)
	{
		aCT_Button_SaveBuilder(
				_button
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Root_ButtonsBuilder(
		myfirstmodule.proxies.Root _root
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Root_Buttons");
		builder = builder.withParam("Root", _root);
		return builder;
	}

	public static java.util.List<myfirstmodule.proxies.Button> dS_Root_Buttons(
		IContext context,
		myfirstmodule.proxies.Root _root
	)
	{
		Object result = dS_Root_ButtonsBuilder(
				_root
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> myfirstmodule.proxies.Button.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Root_GetOrCreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Root_GetOrCreate");
		return builder;
	}

	public static myfirstmodule.proxies.Root dS_Root_GetOrCreate(IContext context)
	{
		Object result = dS_Root_GetOrCreateBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Root.initialize(context, (IMendixObject) result);
	}
}
